version: 2.1

orbs:
  v12: twuni/nodejs@12.10.0

workflows:
  v12:
    jobs:
    - v12/initialize
    - v12/install:
        requires:
        - v12/initialize
    - v12/style:
        requires:
        - v12/install
    - v12/build:
        requires:
        - v12/install
    - v12/test:
        requires:
        - v12/install
