#!/usr/bin/env bash

SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
BASE_DIR=$(dirname "${SCRIPTS_DIR}")
SOURCE_DIR=${BASE_DIR}/src
NODE_MODULES_DIR=${BASE_DIR}/node_modules

MOCHA=${NODE_MODULES_DIR}/.bin/mocha
ESLINT=${NODE_MODULES_DIR}/.bin/eslint

link_source_dir() {
  unlink_source_dir
  ln -s "${SOURCE_DIR}" "${NODE_MODULES_DIR}/_"
}

unlink_source_dir() {
  rm -fR "${NODE_MODULES_DIR}/_"
}

lint_tests() {
  (
    cd "${SOURCE_DIR}"
    "${ESLINT}" spec.setup.js $(list_test_files)
  ) || exit 1
}

list_test_files() {
  (
    cd "${SOURCE_DIR}"
    find . -type f -name spec.js
  ) | xargs
}

run_mocha() {
  (
    cd "${SOURCE_DIR}"
    NODE_ENV=test \
    "${MOCHA}" \
      $* \
      --require babel-register \
      --require babel-polyfill \
      spec.setup.js \
      $(list_test_files)
  ) || exit 1
}

run_tests() {
  EXIT_CODE=0
  link_source_dir
  run_mocha $* || EXIT_CODE=1
  unlink_source_dir
  exit ${EXIT_CODE}
}

lint_tests && run_tests $*
